language: python
python:
- "3.5.1"
before_install:
    - sudo apt-get install sqlite3 libsqlite3-dev.
install: "pip install -r requirements.txt"
script: coverage run  --include="blog/*" --omit="blog/migrations/*" manage.py test blog
